version: '3.8'

services:
  leetcode:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "15432:5432"
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresdb:/var/lib/postgresql/data
    tty: true

volumes:
  postgresdb: